#!/bin/bash


DAY=""

while getopts "d:" opt; do
  case ${opt} in
    d)
      DAY=$OPTARG
      ;;
    \?)
      echo "Usage: $0 -d <day>"
      exit 1
      ;;
  esac
done

if [ -z "$DAY" ]; then
  DAY=${PWD##*/}
fi

FNAME=day${DAY}.py

touch $FNAME
echo -e '#!/bin/python\n\n' > $FNAME
echo -e 'import sys\n\n' >> $FNAME
echo -e 'content = sys.stdin.read()' >> $FNAME 
chmod 755 $FNAME
